from alembic import op
import sqlalchemy as sa
revision='0001_initial';down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table('users',sa.Column('id',sa.Integer,primary_key=True),sa.Column('full_name',sa.String(120),nullable=False),sa.Column('email',sa.String(255),nullable=False,unique=True),sa.Column('phone',sa.String(30)),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',sa.String(30),nullable=False),sa.Column('is_active',sa.Boolean,default=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_index('ix_users_email','users',['email']);op.create_index('ix_users_role','users',['role']);op.create_index('ix_users_is_active','users',['is_active'])
 op.create_table('customers',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='SET NULL'),unique=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('email',sa.String(255),nullable=False),sa.Column('phone',sa.String(30)),sa.Column('company',sa.String(150)),sa.Column('address',sa.Text),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table('categories',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(80),nullable=False,unique=True),sa.Column('description',sa.Text),sa.Column('is_active',sa.Boolean,default=True))
 op.create_table('sla_policies',sa.Column('id',sa.Integer,primary_key=True),sa.Column('priority',sa.String(20),unique=True),sa.Column('response_hours',sa.Integer),sa.Column('resolution_hours',sa.Integer),sa.Column('is_active',sa.Boolean,default=True))
 op.create_table('tickets',sa.Column('id',sa.Integer,primary_key=True),sa.Column('customer_id',sa.Integer,sa.ForeignKey('customers.id',ondelete='CASCADE'),nullable=False),sa.Column('assigned_agent_id',sa.Integer,sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('category_id',sa.Integer,sa.ForeignKey('categories.id',ondelete='SET NULL')),sa.Column('subject',sa.String(200),nullable=False),sa.Column('description',sa.Text,nullable=False),sa.Column('priority',sa.String(20),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('resolved_at',sa.DateTime(timezone=True)),sa.Column('sla_deadline',sa.DateTime(timezone=True)),sa.Column('first_response_at',sa.DateTime(timezone=True)))
 for c in ['customer_id','assigned_agent_id','category_id','priority','status','created_at','sla_deadline']:op.create_index('ix_tickets_'+c,'tickets',[c])
 op.create_table('ticket_comments',sa.Column('id',sa.Integer,primary_key=True),sa.Column('ticket_id',sa.Integer,sa.ForeignKey('tickets.id',ondelete='CASCADE'),nullable=False),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('comment',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table('ticket_attachments',sa.Column('id',sa.Integer,primary_key=True),sa.Column('ticket_id',sa.Integer,sa.ForeignKey('tickets.id',ondelete='CASCADE'),nullable=False),sa.Column('uploaded_by_id',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('file_name',sa.String(255),nullable=False),sa.Column('file_path',sa.String(500),nullable=False),sa.Column('file_size',sa.BigInteger,nullable=False),sa.Column('file_type',sa.String(100),nullable=False),sa.Column('uploaded_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table('notifications',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('title',sa.String(160),nullable=False),sa.Column('message',sa.Text,nullable=False),sa.Column('type',sa.String(40),nullable=False),sa.Column('is_read',sa.Boolean,default=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table('audit_logs',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('action',sa.String(80),nullable=False),sa.Column('entity',sa.String(80),nullable=False),sa.Column('entity_id',sa.Integer,nullable=False),sa.Column('previous_value',sa.Text),sa.Column('new_value',sa.Text),sa.Column('timestamp',sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade():op.drop_table('audit_logs');op.drop_table('notifications');op.drop_table('ticket_attachments');op.drop_table('ticket_comments');op.drop_table('tickets');op.drop_table('sla_policies');op.drop_table('categories');op.drop_table('customers');op.drop_table('users')
