"""create sla table
Revision ID: a16ef5d9dd25
Revises: f9e0f9ef4253
"""
from typing import Sequence,Union
from alembic import op
import sqlalchemy as sa

revision: str = 'a16ef5d9dd25'
down_revision: Union[str, Sequence[str], None] = 'f9e0f9ef4253'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_slas_is_active'), 'slas', ['is_active'], unique=False)
    op.create_index(op.f('ix_slas_priority'), 'slas', ['priority'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slas_priority'), table_name='slas')
    op.drop_index(op.f('ix_slas_is_active'), table_name='slas')
    op.drop_table('slas')
    # ### end Alembic commands ###
